### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by jesephan** [razztyfication/vue-drawing-canvas#13]
Hi im using this package v1.0.8 with Nuxt (v2.15.7) and console is showing an error `Object(...) is not a function` and here is the [full error](https://pastebin.com/7g2rD6Qf)

Wondering if anyone encounter the same and hopefully can help me how to solve this. thanks!

**Comment by razztyfication** [comment]
I assume you are using vue 2

my package depends on vue-demi to support vue 2, maybe the post install script didn't get trigger after installing vue-demi

if you have access to terminal then try this script

`npx vue-demi-switch 2`

**Comment by luacgn** [comment]
Is there any way to fix it ? I am using Vue 2

**Comment by luacgn** [comment]
> Is there any way to fix it ? I am using Vue 2

Solve with Composition API
