### ISSUE TITLE
Not an issue but at question.

### ISSUE THREAD

**Issue by maxrpark** [razztyfication/vue-drawing-canvas#15]
First of all thanks for the package, I had looked at a lot of drawing packages and this is one of the best around and definitely the best one for Vue.

The question is, are you considering improving the erase function. The actual one works kind of ok if you use only color for the background and only if don't change it after you start drawing. 

I am using the package with a background image, so the erase function is not useful at all. At the moment I am using 'undo' if I want to erase something.

I am sure you are aware of this and perhaps don't have a lot of time to improve it. But I think that is the only thing missing from this package to be completely perfect.

So, I hope I  can see this feature in the future.

Thanks again.

**Comment by razztyfication** [comment]
Hello, thank you for your support it means a lot to me.

Yes, i aware the erase function make background image disappear.

the problem to keep the background image is I must cut from one stroke to multiple strokes and that means a lot of work to do on background and it may freeze the browser.

maybe you can give me some ideas?

**Comment by KickSchutte67** [comment]
Hey!

I just came across this package, and facing the same issue as described above. Unfortunately I do not know any solutions to this, but just wanted to bump up this feature since it will enhance the package.

If anyone knows the solution, share it! 

Thanks!

**Comment by razztyfication** [comment]
Hello, can you try this [sandbox](https://codesandbox.io/s/vue-drawing-canvas-1-0-10-rc-2-vn22wx)?

I make some improvements:

- eraser no longer delete background image
- added new value `"line"` on **strokeStyle** to draw straight line
- added new props **[lineCap](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap)** and **[lineJoin](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin)**

Kindly report if you find any bug. Thanks

**Comment by maxrpark** [comment]
Hello Toni!
I am sorry I did not answer before, I wanted to take a look at the package but I have been with a lot of work lately and no time.
The sandbox looks awesome, not only does the erasing work great but all the new features too!

Thank you again for your work, you are proving an excellent package and solution to the Vue dev's community.

Have a nice day!
Max.

**Comment by razztyfication** [comment]
I'll close this issue with the release of [v1.0.10](https://github.com/razztyfication/vue-drawing-canvas/releases/tag/v1.0.10). 
Thanks everyone
