### ISSUE TITLE
Drawing is removed after mouse lift

### ISSUE THREAD

**Issue by Alphazork** [razztyfication/vue-drawing-canvas#20]
I once had a strange error I cannot seem to replicate. The drawn lines got removed the instant I liftet my mouse button.
Lets clarify, mousedown -> mousemove and drawing lines. The canvas shows all the lines -> mouseup -> lines get removed. Nothing is shown.
Version was 1.0.9

Do you have any idea what may have caused this? Sadly it is important because it is a production build. Thank you

**Comment by razztyfication** [comment]
What Vue version do you use?

**Comment by Alphazork** [comment]
Vue version 3.2.21

**Comment by razztyfication** [comment]
Sorry I can't reproduce the issue on this [sandbox] (https://codesandbox.io/s/cranky-sound-6st56v).

Are you use a background image or a watermark image?

Have you tried updating to v.1.0.11?

**Comment by Alphazork** [comment]
The v.1.0.11 has some weird drawing issues, see the picture attached. I would like to update!
Are there bugfixes from 1.0.9 to 1.0.11?
<img width="220" alt="Screen Shot 2022-05-05 at 11 47 08 PM" src="https://user-images.githubusercontent.com/5220095/167031056-4aa59444-5ea0-4271-844d-77cc56b28198.png">

**Comment by razztyfication** [comment]
That's weird, Bug fixes on eraser but that's nothing to do on draw strokes. There Is possibility about lineCap and lineJoin.

Can you provide more information:

- Your browser version
- Did you use any touchscreen device or drawing tablet?
- Can you get me all strokes for that square?

**Comment by Alphazork** [comment]
I see now that the the behavior comes from the lineJoin miter. Other lineJoins work normally.
I will close this issue as I sadly cannot provide you with further information about my original problem. Thank you!
