### ISSUE TITLE
[ERROR] Circle drawing, reading from undefined

### ISSUE THREAD

**Issue by Alphazork** [razztyfication/vue-drawing-canvas#21]
If you draw a circle out of the border and then try to draw again I get the error in the picture.
The whole canvas breaks at this point. Nothing can be drawn and everything gets removed!
I solved the problem with a try and catch inside drawShape.
<img width="444" alt="Screen Shot 2022-05-08 at 5 53 58 PM" src="https://user-images.githubusercontent.com/5220095/167305001-ee327ece-5826-432d-860b-327d5135772c.png">

**Comment by razztyfication** [comment]
Yes, that will solve the issue for now.

it looks like that something is wrong on drawGuide function. it remove previously assigned coordinates.

![image](https://user-images.githubusercontent.com/18417126/167475416-7ae7eda9-ab12-424a-ac92-f0b651b69d20.png)

I'll solve this before publish new version

**Comment by razztyfication** [comment]
Closing this issue with the release of [v1.0.12](https://github.com/razztyfication/vue-drawing-canvas/releases/tag/v1.0.12)
