### ISSUE TITLE
Preview drawing

### ISSUE THREAD

**Issue by KickSchutte67** [razztyfication/vue-drawing-canvas#22]
Hello,

Again, thanks for creating this package. It has helped my project a lot!

I have an issue regarding drawing circles or triangles **over** an image. When I do not use a image, I can see a sort of preview (see screenshot).

![image](https://user-images.githubusercontent.com/31417270/168136490-8097a47b-2e3d-4377-9179-9a439c03cb8d.png)

When using an image to draw over, this circular preview disappears. How do I solve this issue?

**Comment by razztyfication** [comment]
you mean when you set background image the guide is missing?

**Comment by razztyfication** [comment]
I publish beta version of 1.0.13. You can try it or test it on this [sandbox](https://codesandbox.io/s/autumn-dream-40fl2s).

Let me know if you found any bugs.

**Comment by KickSchutte67** [comment]
Your sandbox version solved the issue! 

Can you let me know when this will be released?

**Comment by razztyfication** [comment]
Closing this issue with the release of [1.0.13](https://github.com/razztyfication/vue-drawing-canvas/releases/tag/v1.0.13)
