### ISSUE TITLE
Full width not working

### ISSUE THREAD

**Issue by DominikGanic** [razztyfication/vue-drawing-canvas#25]
Hi, I'm trying to set the the width property to 100% and it doesn't work.
Only with CSS it also doesn't work pretty good, there is a offset of about 20 pixels to the right which doesn't get drawed.

![image](https://user-images.githubusercontent.com/13388387/178262776-2b821a4a-519a-4c55-a5f4-b6f084fc0159.png)

What should I do? Could you add full width support to it?

**Comment by razztyfication** [comment]
You can handle dynamic width and height for canvas by provide parent width and height to canvas.

[this should give you the idea](https://stackblitz.com/edit/vitejs-vite-rhsspb)

Notice the image that you draw is in pixels, that means if you have a canvas with 100px wide and you draw along its width, then you change it to 200px, the lines you drew earlier will still be 100px

<br><br>
P.S. don't forget to handle on window resize
