### ISSUE TITLE
Drawing is buggy with touch (screen attached)

### ISSUE THREAD

**Issue by JimZeeKing** [razztyfication/vue-drawing-canvas#29]
Hi there, here is an image : 
![image](https://user-images.githubusercontent.com/19315887/203148574-6a4ec1df-62a2-4fda-b83b-59f009f0d6dc.png)

The line on the left is made with mouse and the line on the right (if one can call that a line :D) is made while using touch. Any ideas what i could change to circumvent the problem?

**Comment by razztyfication** [comment]
![image](https://user-images.githubusercontent.com/18417126/203297355-f21f7370-733f-43d3-9131-4b822dde09e3.png)

Have you try with lineJoin "round" ?

**Comment by JimZeeKing** [comment]
@razztyfication Yes, still the same, i ended forking it and disabled touch event since mouseevent will be use as fallback and it works.
