### ISSUE TITLE
Can I pass a custom operation history?

### ISSUE THREAD

**Issue by Youky1** [razztyfication/vue-drawing-canvas#30]
I want to save the operation history when user leave the page, and load it **from server** when they come in again.
Can I pass it as a prop to init the operation history?

**Comment by razztyfication** [comment]
maybe you can check this [example](https://codesandbox.io/s/vue-drawing-canvas-107-rc1-dcoiy), you can save your progress in your database instead of localStorage

**Comment by Youky1** [comment]
Thanks!
