### ISSUE TITLE
drawBackgroundImage bug

### ISSUE THREAD

**Issue by pvasilek** [razztyfication/vue-drawing-canvas#4]
'return;' missed in the block below leading to null assignment in the "image.src = this.backgroundImage;" line.
` if (!this.backgroundImage) {
            resolve();
          }`

**Comment by razztyfication** [comment]
hello @pvasilek,
sry i dont get it. can you explain more?

**Comment by pvasilek** [comment]
Because of missed return your code continue execution and make a null assigment to image.src which requesting browser to make the calls to http(s)://web-site/null lead 404.
Use you code and check Chrome console log.

**Comment by razztyfication** [comment]
got it, currently working on it

**Comment by razztyfication** [comment]
fixed on v1.0.5.

closing this now, thanks
