### ISSUE TITLE
Triangle/Square/Half-Triangle Drawing issue

### ISSUE THREAD

**Issue by Sovaidsyed** [razztyfication/vue-drawing-canvas#5]
All different shapes except for circle don't completely render they always miss a line

**Comment by Alphazork** [comment]
I have created a pull request that should fix that. But just add {x: this.strokes.from.x, y: this.strokes.from.y} to the shapes to fix it immediately.

**Comment by razztyfication** [comment]
published v1.0.5.

closing this now, thanks
