### ISSUE TITLE
Use previously saved Drawing  for editing

### ISSUE THREAD

**Issue by Sovaidsyed** [razztyfication/vue-drawing-canvas#8]
I saved the image in base64 string in my database now I want to use it again for editing to add new content in the same drawing. Is there a way to do it?

**Comment by razztyfication** [comment]
if you want to add new content to previously saved image maybe you can use it as bg image then start add new content

but if you want to edit previously saved image then you must save all strokes and shapes instead of base64 image and for now it can't

**Comment by Sovaidsyed** [comment]
Alright so what if we draw the image again in canvas by getting the canvas from the canvas id and then just draw the image that we have so far?

**Comment by razztyfication** [comment]
so you trying to save the canvas element then on the new page you use the canvas  you saved before and start drawing on it?

**Comment by Sovaidsyed** [comment]
I tried to do it but the problem I am facing is that the image do get redrawn and rendered but once you start to edit the old one altogether gets lost.

**Comment by razztyfication** [comment]
what if I add a new method to get all the strokes and shapes, then you can render a new canvas with the initial image?

but first i need to make sure no issue on this idea

**Comment by Sovaidsyed** [comment]
Sorry for that I was kind of busy these days. So I just wanted to know will this way somehow be able to edit the previous image if the new canvas is rendered.

**Comment by razztyfication** [comment]
yes you can, but you must change your saved data from base64 image to all strokes path

please kindly check this [example](https://codesandbox.io/s/vue-drawing-canvas-107-rc1-dcoiy). try draw something and press *__"Save All Strokes"__* button then refresh codesandbox workspace to see your previously saved image as an initial image.

**Comment by Sovaidsyed** [comment]
Yes something like this, you used localStorage so if I save the image in my database as using this method instead of local storage and getting it in the initial image I guess it would work for me too right?

**Comment by razztyfication** [comment]
Yep, added on 1.0.7

closing this now, thanks
