### ISSUE TITLE
Text Functionality Canvas

### ISSUE THREAD

**Issue by Sovaidsyed** [razztyfication/vue-drawing-canvas#9]
Is there a way to add text to the vue drawing canvas? If not is there a way to add it to the canvas? I tried to add in the canvas but when I suddenly tried to draw on it the text was instantly removed.

**Comment by razztyfication** [comment]
You can add text to canvas for watermark, or you can convert your text as image then use it as bg image

**Comment by Sovaidsyed** [comment]
Hi, I really do want this functionality to have it since it completes the whole concept of my whiteboard functionality if there is a way other than a watermark like a start entering text on the point you just clicked something like. If you are having trouble with it maybe I'll do it, you could let me know.
<img width="1013" alt="Screenshot 2021-12-29 at 1 52 56 PM" src="https://user-images.githubusercontent.com/48292264/147644571-92f29be9-a9b8-42c4-be74-7719f07aa928.png">

**Comment by razztyfication** [comment]
sure, PR are very welcome.

can you explain what you gonna do?
